/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package br.com.archbase.query.rsql.parser;


/**
 * Valores literais de token e constantes.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
interface ParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int ALPHA = 3;
    /**
     * RegularExpression Id.
     */
    int ESCAPED_CHAR = 4;
    /**
     * RegularExpression Id.
     */
    int UNRESERVED_STR = 5;
    /**
     * RegularExpression Id.
     */
    int SINGLE_QUOTED_STR = 6;
    /**
     * RegularExpression Id.
     */
    int DOUBLE_QUOTED_STR = 7;
    /**
     * RegularExpression Id.
     */
    int AND = 8;
    /**
     * RegularExpression Id.
     */
    int OR = 9;
    /**
     * RegularExpression Id.
     */
    int LPAREN = 10;
    /**
     * RegularExpression Id.
     */
    int RPAREN = 11;
    /**
     * RegularExpression Id.
     */
    int COMP_FIQL = 12;
    /**
     * RegularExpression Id.
     */
    int COMP_ALT = 13;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "<ALPHA>",
            "<ESCAPED_CHAR>",
            "<UNRESERVED_STR>",
            "<SINGLE_QUOTED_STR>",
            "<DOUBLE_QUOTED_STR>",
            "<AND>",
            "<OR>",
            "\"(\"",
            "\")\"",
            "<COMP_FIQL>",
            "<COMP_ALT>",
    };

}
